# Generated by Django 4.0 on 2023-04-25 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='workerks',
            field=models.ManyToManyField(through='backend.Workers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workers',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.company'),
        ),
        migrations.AddField(
            model_name='workers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
