# Generated by Django 4.0 on 2023-04-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_workers_company_workerks_workers_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='workerks',
            new_name='users',
        ),
    ]
